name: findpix_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #stacked
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  stacked_firebase_auth: ^2.19.6

  #firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  firebase_database: ^10.3.4

  # basic
  flutter_native_splash: ^2.3.2

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

  #basic
  flutter_launcher_icons: ^0.13.1

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.jpg"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
