name: autocare_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  imageview360: ^1.3.0
  google_maps_flutter: ^2.5.0
  pdf: ^3.8.4
  open_file: ^3.3.2
  path_provider: ^2.1.1

  #stacked -
  stacked: ^3.4.1
  stacked_services: ^1.3.0
  stacked_firebase_auth: ^2.19.6

  # firebase - flutterfire configure
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_database: ^10.3.6

  # basic
  flutter_native_splash: ^2.2.15

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: "^0.11.0"

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.jpg"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/car/
    - assets/bike/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
